
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.HBox hbox1;
	private global::Gtk.Button btnOpen;
	private global::Gtk.Entry txtFileName;
	private global::Gtk.VBox vbox2;
	private global::Gtk.HBox hbox3;
	private global::Gtk.Label label5;
	private global::Gtk.Label lbWriteTime;
	private global::Gtk.HBox hbox4;
	private global::Gtk.Label label7;
	private global::Gtk.Label lbFileName;
	private global::Gtk.HBox hbox5;
	private global::Gtk.Label label8;
	private global::Gtk.Label lbFileSize;
	private global::Gtk.Label label1;
	private global::Gtk.Entry txtTitle;
	private global::Gtk.Label label2;
	private global::Gtk.Entry txtArtist;
	private global::Gtk.Label label3;
	private global::Gtk.Entry txtAlbum;
	private global::Gtk.Label label9;
	private global::Gtk.Entry txtYear;
	private global::Gtk.Label label4;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TextView txtComments;
	private global::Gtk.HBox hbox2;
	private global::Gtk.Label lbMsg;
	private global::Gtk.Label lbError;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Read a mp3 file");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(3));
		this.Resizable = false;
		this.DefaultWidth = 400;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		this.vbox1.BorderWidth = ((uint)(6));
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnOpen = new global::Gtk.Button ();
		this.btnOpen.CanFocus = true;
		this.btnOpen.Name = "btnOpen";
		this.btnOpen.UseStock = true;
		this.btnOpen.UseUnderline = true;
		this.btnOpen.Label = "gtk-open";
		this.hbox1.Add (this.btnOpen);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnOpen]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.txtFileName = new global::Gtk.Entry ();
		this.txtFileName.CanFocus = true;
		this.txtFileName.Name = "txtFileName";
		this.txtFileName.IsEditable = false;
		this.txtFileName.InvisibleChar = '•';
		this.hbox1.Add (this.txtFileName);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.txtFileName]));
		w2.PackType = ((global::Gtk.PackType)(1));
		w2.Position = 1;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		this.hbox3.BorderWidth = ((uint)(3));
		// Container child hbox3.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Write Time: ");
		this.hbox3.Add (this.label5);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label5]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.lbWriteTime = new global::Gtk.Label ();
		this.lbWriteTime.Name = "lbWriteTime";
		this.hbox3.Add (this.lbWriteTime);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.lbWriteTime]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		this.vbox2.Add (this.hbox3);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox3]));
		w6.Position = 0;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		this.hbox4.BorderWidth = ((uint)(3));
		// Container child hbox4.Gtk.Box+BoxChild
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("File Name: ");
		this.hbox4.Add (this.label7);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label7]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.lbFileName = new global::Gtk.Label ();
		this.lbFileName.Name = "lbFileName";
		this.hbox4.Add (this.lbFileName);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.lbFileName]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		this.vbox2.Add (this.hbox4);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox4]));
		w9.Position = 1;
		w9.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		this.hbox5.BorderWidth = ((uint)(3));
		// Container child hbox5.Gtk.Box+BoxChild
		this.label8 = new global::Gtk.Label ();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("File Size: ");
		this.hbox5.Add (this.label8);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label8]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.lbFileSize = new global::Gtk.Label ();
		this.lbFileSize.Name = "lbFileSize";
		this.hbox5.Add (this.lbFileSize);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.lbFileSize]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		this.vbox2.Add (this.hbox5);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox5]));
		w12.Position = 2;
		w12.Expand = false;
		this.vbox1.Add (this.vbox2);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox2]));
		w13.Position = 1;
		w13.Expand = false;
		w13.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Title:");
		this.vbox1.Add (this.label1);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label1]));
		w14.Position = 2;
		w14.Expand = false;
		w14.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.txtTitle = new global::Gtk.Entry ();
		this.txtTitle.CanFocus = true;
		this.txtTitle.Name = "txtTitle";
		this.txtTitle.IsEditable = true;
		this.txtTitle.InvisibleChar = '●';
		this.vbox1.Add (this.txtTitle);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.txtTitle]));
		w15.Position = 3;
		w15.Expand = false;
		w15.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Artist:");
		this.vbox1.Add (this.label2);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label2]));
		w16.Position = 4;
		w16.Expand = false;
		w16.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.txtArtist = new global::Gtk.Entry ();
		this.txtArtist.CanFocus = true;
		this.txtArtist.Name = "txtArtist";
		this.txtArtist.IsEditable = true;
		this.txtArtist.InvisibleChar = '●';
		this.vbox1.Add (this.txtArtist);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.txtArtist]));
		w17.Position = 5;
		w17.Expand = false;
		w17.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Album:");
		this.vbox1.Add (this.label3);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label3]));
		w18.Position = 6;
		w18.Expand = false;
		w18.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.txtAlbum = new global::Gtk.Entry ();
		this.txtAlbum.CanFocus = true;
		this.txtAlbum.Name = "txtAlbum";
		this.txtAlbum.IsEditable = true;
		this.txtAlbum.InvisibleChar = '●';
		this.vbox1.Add (this.txtAlbum);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.txtAlbum]));
		w19.Position = 7;
		w19.Expand = false;
		w19.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.label9 = new global::Gtk.Label ();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Year:");
		this.vbox1.Add (this.label9);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label9]));
		w20.Position = 8;
		w20.Expand = false;
		w20.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.txtYear = new global::Gtk.Entry ();
		this.txtYear.CanFocus = true;
		this.txtYear.Name = "txtYear";
		this.txtYear.IsEditable = true;
		this.txtYear.InvisibleChar = '●';
		this.vbox1.Add (this.txtYear);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.txtYear]));
		w21.Position = 9;
		w21.Expand = false;
		w21.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Comments:");
		this.vbox1.Add (this.label4);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label4]));
		w22.Position = 10;
		w22.Expand = false;
		w22.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.txtComments = new global::Gtk.TextView ();
		this.txtComments.CanFocus = true;
		this.txtComments.Name = "txtComments";
		this.GtkScrolledWindow.Add (this.txtComments);
		this.vbox1.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
		w24.Position = 11;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.lbMsg = new global::Gtk.Label ();
		this.lbMsg.Name = "lbMsg";
		this.hbox2.Add (this.lbMsg);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.lbMsg]));
		w25.Position = 0;
		w25.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.lbError = new global::Gtk.Label ();
		this.lbError.Name = "lbError";
		this.hbox2.Add (this.lbError);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.lbError]));
		w26.Position = 1;
		w26.Fill = false;
		this.vbox1.Add (this.hbox2);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
		w27.Position = 12;
		w27.Expand = false;
		w27.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultHeight = 453;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.btnOpen.Clicked += new global::System.EventHandler (this.OnBtnOpenClicked);
	}
}
